# ==========================================
# SERVER
# ==========================================
spring.application.name=agro-erp-backend
#server.port=8080
##server.servlet.context-path=/api
#
## ==========================================
## DATABASE



server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
## ==========================================
#spring.datasource.url=jdbc:mysql://localhost:3306/agro_erp_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## ==========================================
## JPA / HIBERNATE
## ==========================================
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================================
# JWT
# ==========================================
app.jwt.secret=agroErpJwtSecretKey2024VeryLongSecretKeyForProductionUse256Bits
app.jwt.expiration-ms=86400000

# ==========================================
# LOGGING
# ==========================================
logging.level.com.agroerp=DEBUG
logging.level.org.springframework.security=DEBUG

server.address=0.0.0.0